- name: Ensure that tzdata is installed
  apt: pkg=tzdata state=present update_cache=yes

- name: Set timezone in system configuration
  template: src=timezone.j2 dest=/etc/timezone
  when: (ansible_date_time.tz != clock_timezone) and ansible_service_mgr != 'systemd'

- name: Update /etc/localtime
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: (ansible_date_time.tz != clock_timezone) and ansible_service_mgr != 'systemd'
  notify:
    - Sync hardware clock

- name: Set timezone
  command: timedatectl set-timezone {{ clock_timezone }}
  when: (ansible_date_time.tz != clock_timezone) and ansible_service_mgr == 'systemd'
  notify:
    - Sync hardware clock
