- name: Ensure that tzdata is installed
  yum: name=tzdata state=present

- include: EL7.yml
  when: ansible_distribution_major_version == '7'

- include: EL6.yml
  when: ansible_distribution_major_version == '6'

