require 'rake'
require 'rspec/core/rake_task'

role = 'clock'

hosts = %w(
  centos7
  centos6
  precise
  trusty
  wheezy
)

task :spec => 'spec:all'

namespace :spec do
  task :all => hosts.map {|h| 'spec:' + h.split('.')[0] }
  hosts.each do |host|
    desc "Run serverspec to #{host}"
    RSpec::Core::RakeTask.new(host) do |t|
      ENV['TARGET_HOST'] = host
      t.pattern = "spec/#{role}/*_spec.rb"
    end
  end
end
